import type { Plan, User } from '@/types'

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    full_name: 'Arjun Mehta',
    username: 'arjun.mehta',
    avatar_url: 'https://i.pravatar.cc/150?img=11',
    photos: ['https://i.pravatar.cc/400?img=11', 'https://i.pravatar.cc/400?img=12'],
    interests: ['Running', 'Cafe hopping', 'Photography'],
    city: 'Mumbai',
    dob: '1997-04-12',
    gender: 'Male',
    is_verified: true,
    is_free_now: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'u2',
    full_name: 'Priya Sharma',
    username: 'priya.sharma',
    avatar_url: 'https://i.pravatar.cc/150?img=47',
    photos: ['https://i.pravatar.cc/400?img=47', 'https://i.pravatar.cc/400?img=48'],
    interests: ['Yoga', 'Travel', 'Content creation'],
    city: 'Mumbai',
    dob: '1999-08-22',
    gender: 'Female',
    is_verified: true,
    is_free_now: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'u3',
    full_name: 'Rohan Kapoor',
    username: 'rohan.kapoor',
    avatar_url: 'https://i.pravatar.cc/150?img=15',
    photos: ['https://i.pravatar.cc/400?img=15'],
    interests: ['Gym', 'Startups', 'Coding'],
    city: 'Mumbai',
    dob: '1995-01-30',
    gender: 'Male',
    is_verified: false,
    is_free_now: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'u4',
    full_name: 'Meera Nair',
    username: 'meera.nair',
    avatar_url: 'https://i.pravatar.cc/150?img=44',
    photos: ['https://i.pravatar.cc/400?img=44', 'https://i.pravatar.cc/400?img=45'],
    interests: ['Music', 'Movies', 'Hangouts'],
    city: 'Mumbai',
    dob: '2000-11-05',
    gender: 'Female',
    is_verified: true,
    is_free_now: false,
    created_at: new Date().toISOString(),
  },
]

const now = new Date()

export const MOCK_PLANS: Plan[] = [
  {
    id: 'p1',
    creator_id: 'u1',
    creator: MOCK_USERS[0],
    mode: 'NOW',
    title: 'Cycling along Marine Drive',
    description: 'Quick 45-min ride. Bring your cycle or rent one near the gate!',
    location: 'Marine Drive, Mumbai',
    lat: 18.9432,
    lng: 72.8236,
    starts_at: new Date(now.getTime() + 20 * 60000).toISOString(),
    ends_at: new Date(now.getTime() + 80 * 60000).toISOString(),
    max_people: 6,
    joined_count: 3,
    tags: ['Cycling', 'Fitness', 'Outdoors'],
    is_active: true,
    created_at: new Date(now.getTime() - 5 * 60000).toISOString(),
    has_joined: false,
  },
  {
    id: 'p2',
    creator_id: 'u2',
    creator: MOCK_USERS[1],
    mode: 'NOW',
    title: 'Cafe study session – Starbucks BKC',
    description: 'Working on my laptop, come join if you want company 🎧',
    location: 'Starbucks, BKC',
    lat: 19.0596,
    lng: 72.8656,
    starts_at: new Date(now.getTime() + 5 * 60000).toISOString(),
    ends_at: new Date(now.getTime() + 120 * 60000).toISOString(),
    max_people: 4,
    joined_count: 1,
    tags: ['Study', 'Cafe', 'Work'],
    is_active: true,
    created_at: new Date(now.getTime() - 2 * 60000).toISOString(),
    has_joined: false,
  },
  {
    id: 'p3',
    creator_id: 'u3',
    creator: MOCK_USERS[2],
    mode: 'NOW',
    title: 'Walk & talk near Bandra',
    description: 'Just want to get some steps in and have a good chat',
    location: 'Carter Road, Bandra',
    lat: 19.0607,
    lng: 72.8362,
    starts_at: new Date(now.getTime() + 10 * 60000).toISOString(),
    ends_at: new Date(now.getTime() + 70 * 60000).toISOString(),
    max_people: 3,
    joined_count: 2,
    tags: ['Walk', 'Social', 'Outdoors'],
    is_active: true,
    created_at: new Date(now.getTime() - 8 * 60000).toISOString(),
    has_joined: false,
  },
  {
    id: 'p4',
    creator_id: 'u4',
    creator: MOCK_USERS[3],
    mode: 'SOON',
    title: 'Run Club – Sunday Morning',
    description: 'Weekly 5K run with a fun group. All paces welcome!',
    location: 'Joggers Park, Bandra',
    lat: 19.0553,
    lng: 72.8248,
    starts_at: new Date(now.getTime() + 2 * 24 * 60 * 60000).toISOString(),
    ends_at: new Date(now.getTime() + 2 * 24 * 60 * 60000 + 90 * 60000).toISOString(),
    max_people: 20,
    joined_count: 12,
    tags: ['Running', 'Fitness', 'Weekend'],
    is_active: true,
    created_at: new Date(now.getTime() - 2 * 60 * 60000).toISOString(),
    has_joined: false,
  },
  {
    id: 'p5',
    creator_id: 'u1',
    creator: MOCK_USERS[0],
    mode: 'SOON',
    title: 'Cafe meetup – Tomorrow evening',
    description: 'Chill hangout, good coffee, better conversation ☕',
    location: 'Blue Tokai, Andheri',
    lat: 19.1136,
    lng: 72.8697,
    starts_at: new Date(now.getTime() + 1 * 24 * 60 * 60000 + 18 * 60 * 60000).toISOString(),
    ends_at: new Date(now.getTime() + 1 * 24 * 60 * 60000 + 20 * 60 * 60000).toISOString(),
    max_people: 8,
    joined_count: 5,
    tags: ['Cafe', 'Social', 'Hangout'],
    is_active: true,
    created_at: new Date(now.getTime() - 3 * 60 * 60000).toISOString(),
    has_joined: false,
  },
  {
    id: 'p6',
    creator_id: 'u2',
    creator: MOCK_USERS[1],
    mode: 'COLLAB',
    title: 'Looking for a photography partner',
    description: 'Shooting street portraits this weekend. Need someone good with natural light.',
    location: 'Dharavi, Mumbai',
    lat: 19.0421,
    lng: 72.8531,
    starts_at: new Date(now.getTime() + 3 * 24 * 60 * 60000).toISOString(),
    max_people: 2,
    joined_count: 0,
    tags: ['Photography', 'Creator', 'Weekend'],
    collab_category: 'Photography',
    is_active: true,
    created_at: new Date(now.getTime() - 1 * 60 * 60000).toISOString(),
    has_joined: false,
  },
  {
    id: 'p7',
    creator_id: 'u3',
    creator: MOCK_USERS[2],
    mode: 'COLLAB',
    title: 'Co-founder wanted – SaaS startup',
    description: 'Building a B2B SaaS tool. Looking for a tech co-founder. Have funding interest.',
    location: 'Worli, Mumbai',
    lat: 18.9987,
    lng: 72.8172,
    starts_at: new Date(now.getTime() + 1 * 24 * 60 * 60000).toISOString(),
    max_people: 2,
    joined_count: 1,
    tags: ['Startup', 'Coding', 'Business'],
    collab_category: 'Startup / coding',
    is_active: true,
    created_at: new Date(now.getTime() - 4 * 60 * 60000).toISOString(),
    has_joined: false,
  },
]

export const INTERESTS = {
  Fitness: ['Running', 'Gym', 'Cycling', 'Yoga', 'Sports'],
  Creators: ['Content creation', 'Photography', 'Videography', 'Influencer collabs', 'Editing'],
  Social: ['Cafe hopping', 'Hangouts', 'Movies', 'Music', 'Parties'],
  Learning: ['Study groups', 'Coding', 'Business', 'Startups'],
  Lifestyle: ['Travel', 'Food exploration', 'Events', 'Night outs'],
  Fun: ['Gaming', 'Board games', 'Sports watching'],
}

export const COLLAB_CATEGORIES = [
  { label: 'Content creation', icon: '🎬' },
  { label: 'Photography', icon: '📸' },
  { label: 'Videography', icon: '🎥' },
  { label: 'Fitness partners', icon: '💪' },
  { label: 'Startup / coding', icon: '🚀' },
  { label: 'Influencer collabs', icon: '✨' },
]
